[licenses]
allow = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-2-Clause", "BSD-3-Clause", "CDLA-Permissive-2.0", "ISC", "MPL-2.0", "OpenSSL", "Unicode-3.0", "Unicode-DFS-2016", "Zlib"]

[advisories]
ignore = []

[bans]
multiple-versions = "warn"
deny = [
    { name = "openssl" },
    { name = "openssl-sys" },
]

[sources]
allow-git = false
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
